### ISSUE TITLE
Error running in QGIS

### ISSUE THREAD

**Issue by cdhasselerharm** [deepbands/deep-learning-datasets-maker#8]
Using on a tiff image with 4 bands RGB and alpha
QGIS 3.22.4

2022-03-10T15:24:22     WARNING    Traceback (most recent call last):
              File "C:\Users/Chris/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deep-learning-datasets-maker\split_rs_data.py", line 315, in run
              rasterize(ras_path, vec_path, output)
              File "C:\Users/Chris/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deep-learning-datasets-maker\utils\rasterize.py", line 11, in rasterize
              lyr = vec_ds.GetLayer()
             AttributeError: 'NoneType' object has no attribute 'GetLayer'

**Comment by cdhasselerharm** [comment]
Now getting:

Traceback (most recent call last):
  File "C:\Users/Chris/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deep-learning-datasets-maker\split_rs_data.py", line 315, in run
    rasterize(ras_path, vec_path, output)
  File "C:\Users/Chris/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deep-learning-datasets-maker\utils\rasterize.py", line 8, in rasterize
    ras_ds = gdal.Open(ras_path)
  File "C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg\osgeo\gdal.py", line 4112, in Open
    return _gdal.Open(*args)
RuntimeError: `G:\My Drive\...\annotations\trial.geojson' not recognized as a supported file format.

**Comment by mazingaro** [comment]
I had the same (using GPKG). I am still not sure why, but it works with SHP.
